pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'MultiWorkspace'

include 'NovaCore'
//include 'GalacticResources'
include 'ExNihiloSequentia'
//include 'ExNihiloJEI'
//include 'ExNihiloTOP'
//include 'ExNihiloMekanism'
//include 'ExNihiloJade'

//include 'ExNihiloKubeJs'
//include 'ExNihiloThermal'
//include 'ExNihiloCraftTweaker'
//include 'ExNihiloAE'

include 'workspace'
